name: Deploy Event Management Client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t tony26112004/event-management-client --build-arg VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}' --build-arg VITE_CLIENT_URL='${{ secrets.VITE_CLIENT_URL }}' --build-arg VITE_NODE_ENV='production' .
        
      - name: Publish Image to docker hub
        run: docker push tony26112004/event-management-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tony26112004/event-management-client:latest
        
      - name: Clean up old containers and port conflicts
        run: |
          docker stop event-management-client-container 2>/dev/null || true
          docker rm event-management-client-container 2>/dev/null || true
          
          # Dừng bất kỳ process nào đang dùng port 80 (trừ API)
          sudo fuser -k 80/tcp 2>/dev/null || true
        
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name event-management-client-container --restart unless-stopped tony26112004/event-management-client
        
      - name: Verify deployment
        run: |
          sleep 10
          docker ps | grep event-management-client-container
          curl -f http://localhost || echo "Client app is starting..."